In [ ]:
!pip install nltk

In [ ]:
import torch
import torch.nn as nn
import numpy as np
import nltk
from torch.utils.data import Dataset,DataLoader
from collections import Counter
from nltk.tokenize import word_tokenize
nltk.download('punkt')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from collections import Counter
from nltk.tokenize import word_tokenize
import nltk

nltk.download('punkt_tab')

text = "Natural Language language Processing with Python and NLTK is fun. NLTK makes it easier!"


tokens = word_tokenize(text.lower())

word_freq = Counter(tokens)

for tok in word_freq.keys():
  print(tok)
# print(tokens)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


natural
language
processing
with
python
and
nltk
is
fun
.
makes
it
easier
!


In [ ]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [ ]:
tokens = word_tokenize(document.lower())
word_count = Counter(tokens)

vocab = {"<unk>":0}
for word in word_count.keys():
  if word not in vocab:
    vocab[word] = len(vocab)
# print(len(vocab))

input_sentences = document.split('\n')
# input_sentences


In [ ]:
def text_to_int(sentence,vocab):
  toks = word_tokenize(sentence)
  li = []
  for tok in toks:
    if tok in vocab:
      li.append(vocab[tok])
    else:
      li.append(vocab['<unk>'])
  return li

input_numerical_sentences = []
for senetence in input_sentences:
  input_numerical_sentences.append(text_to_int(senetence.lower(),vocab))
# input_numerical_sentences[2]

In [ ]:
training_sequence = []
for sent in input_numerical_sentences:

  for i in range(1,len(sent)):
    training_sequence.append(sent[:i+1])
training_sequence[:5]

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6]]

In [ ]:
lens = []
for i in range(len(training_sequence)):
  lens.append(len(training_sequence[i]))

max_len = max(lens)
padded_training_sequence = []
for i in training_sequence:
  padded_training_sequence.append([0]*(max_len - len(i)) + i)
  # print(i)
  # break
padded_training_sequence = torch.tensor(padded_training_sequence,dtype = torch.long)
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [ ]:
X = padded_training_sequence[:,:-1]
y = padded_training_sequence[:,-1]
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X = X
    self.y = y
  def __len__(self):
    return len(y)
  def __getitem__(self,index):
    return X[index],y[index]

dataset = CustomDataset(X,y)
dataloader =  DataLoader(dataset,shuffle = True,batch_size = 32)
# dataset[1][1]
# for input,output in dataloader:
#   print(input,output)

tensor([[  0,   0,   0,  ...,  27,   2,   6],
        [  0,   0,   0,  ...,  91,  27,   2],
        [  0,   0,   0,  ...,  22,  23,  24],
        ...,
        [  0,   0,   0,  ...,  65,  86, 236],
        [  0,   0,   0,  ...,   2,  48,  49],
        [  0,   0,   0,  ...,  24, 265, 262]]) tensor([ 33,  89,  25, 176, 253,  27,  36, 188,  97,  76,  19, 164, 195, 110,
        131,   8,   5,  36, 275, 258, 147,   2, 200,  76, 154,  26,  79, 156,
         85, 237,  50, 252])
tensor([[  0,   0,   0,  ...,  24, 100,  93],
        [  0,   0,   0,  ..., 149,  22,  45],
        [  0,   0,   0,  ...,  73, 252, 253],
        ...,
        [  0,   0,   0,  ...,  22,  23,  24],
        [  0,   0,   0,  ...,  26,  27,  28],
        [  0,   0,   0,  ...,  81, 146,  24]]) tensor([  2,  46, 170,   6,   2,  17, 166, 151,  21,  45,  85,  22,  73,  30,
        142,  86,  22, 142,  22,  93,   2, 223,   6,  72,  22,  80, 103, 151,
          8, 179,  29,  25])
tensor([[  0,   0,   0,  ...,  37,  38,  39],
    

In [ ]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,100)
    # lstm ke NN ke andar kitne neurons rkhna hai here 150
    self.lstm = nn.LSTM(100,150,batch_first = True)
    self.fc = nn.Linear(150,vocab_size)
  def forward(self,x):
    x = self.embedding(x)
    intermediate_hidden_state,(final_hidden_state,final_cell_state) = self.lstm(x)
    x = self.fc(final_hidden_state.squeeze(0))
    return x

model = LSTMModel(len(vocab))
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
model = model.to(device)
epochs = 50
lr = 0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr = lr)

for ep in range(epochs):
  total_loss = 0
  for input,output in dataloader:
    input = input.to(device)
    output = output.to(device)

    y_pred = model(input)
    loss = criterion(y_pred,output)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    total_loss += loss.item()
  print(f"epoch : {ep} , loss : {total_loss}")


cpu
epoch : 0 , loss : 165.16024541854858
epoch : 1 , loss : 145.65811252593994
epoch : 2 , loss : 132.76080465316772
epoch : 3 , loss : 121.05112147331238
epoch : 4 , loss : 108.77711534500122
epoch : 5 , loss : 97.53946590423584
epoch : 6 , loss : 87.72150611877441
epoch : 7 , loss : 78.59044003486633
epoch : 8 , loss : 69.59177017211914
epoch : 9 , loss : 61.73288416862488
epoch : 10 , loss : 54.55937433242798
epoch : 11 , loss : 47.86414837837219
epoch : 12 , loss : 42.57727134227753
epoch : 13 , loss : 37.48120582103729
epoch : 14 , loss : 32.78972613811493
epoch : 15 , loss : 28.96329563856125
epoch : 16 , loss : 25.848844468593597
epoch : 17 , loss : 22.66919705271721
epoch : 18 , loss : 20.461706697940826
epoch : 19 , loss : 18.36601397395134
epoch : 20 , loss : 16.348941028118134
epoch : 21 , loss : 14.982006043195724
epoch : 22 , loss : 13.429389297962189
epoch : 23 , loss : 12.374469697475433
epoch : 24 , loss : 11.336917608976364
epoch : 25 , loss : 10.646251603960991
epoch

In [ ]:
def predict(sentence):
  snt = sentence.lower() # Pass the original string to text_to_int
  numerical_text = text_to_int(snt,vocab)
  padded_text = [0]*(max_len - len(numerical_text)) + numerical_text
  padded_text = torch.tensor(padded_text,dtype = torch.long).unsqueeze(0).to(device) # Move tensor to device
  output = model(padded_text)
  # print(output.shape)

  val,ind = torch.max(output,axis = 1)
  return sentence + " " + list(vocab.keys())[ind.item()]
predict("The course follows a ")

'The course follows a  monthly'